'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: build
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verification
        run: go mod verify
      - name: Tidy
        if: matrix.go-version == '1.16.x'
        run: go mod tidy
      - name: Build
        run: go build main.go